name: test docker auth
on:
    workflow_dispatch:
jobs:
    build-and-push-image:
        runs-on: ubuntu-latest        
        steps:
            - name: Login to Docker Hub
              uses: meta-introspector/login-action@v3
              with:
                username: ${{ vars.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
